/* DON ZOILO V34.0 — MÓDULO CAJA Y ACTIVOS */
(function(){
'use strict';
const TABLE='current_assets', LOCAL_KEY='don_zoilo_current_assets_v34';
const TYPES={cash:'Caja',checks:'Cheques',bank:'Bancos y billeteras',personal_receivable:'Clientes particulares'};
let rows=[];
const $=id=>document.getElementById(id);
const uuid=()=>crypto.randomUUID?crypto.randomUUID():`asset-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const num=v=>{if(typeof v==='number')return Number.isFinite(v)?v:0;const t=String(v??'').trim().replace(/\$/g,'').replace(/\s/g,'').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.');const n=Number(t);return Number.isFinite(n)?n:0};
const money=v=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(num(v));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const cloud=()=>typeof window.supabaseClient!=='undefined'&&window.supabaseClient;
function localRead(){try{return JSON.parse(localStorage.getItem(LOCAL_KEY)||'[]')}catch(_){return[]}}
function localWrite(){localStorage.setItem(LOCAL_KEY,JSON.stringify(rows))}
function defaults(){const now=new Date().toISOString();return[
{id:uuid(),asset_type:'cash',name:'EFECTIVO',balance:0,notes:'',sort_order:10},
{id:uuid(),asset_type:'checks',name:'CHEQUES EN CARTERA',balance:0,notes:'',sort_order:20},
{id:uuid(),asset_type:'bank',name:'BANCO NACIÓN',balance:0,notes:'',sort_order:30},
{id:uuid(),asset_type:'bank',name:'MERCADO PAGO',balance:0,notes:'',sort_order:40},
{id:uuid(),asset_type:'bank',name:'UALÁ',balance:0,notes:'',sort_order:50},
{id:uuid(),asset_type:'bank',name:'GALICIA',balance:0,notes:'',sort_order:60},
{id:uuid(),asset_type:'bank',name:'CUENTA ROMI',balance:0,notes:'',sort_order:70}
].map(r=>({...r,created_at:now,updated_at:now}))}
function injectStyles(){if($('currentAssetsStyles'))return;const s=document.createElement('style');s.id='currentAssetsStyles';s.textContent=`#currentAssets .assets-head{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;margin-bottom:14px}#currentAssets .assets-summary{display:grid;grid-template-columns:repeat(5,minmax(145px,1fr));gap:10px;margin:14px 0 18px}#currentAssets .asset-card{background:#fff;border:1px solid #d9dee7;border-radius:12px;padding:12px}#currentAssets .asset-card span{display:block;color:#667085;font-size:.8rem;margin-bottom:5px}#currentAssets .asset-card.total{background:#101820;color:#fff}#currentAssets .asset-card.total span{color:#d0d5dd}#currentAssets .asset-group{background:#fff;border:1px solid #d9dee7;border-radius:12px;margin-bottom:14px;overflow:hidden}#currentAssets .asset-group-head{display:flex;justify-content:space-between;align-items:center;padding:12px;background:#eef5f7;border-bottom:1px solid #d9dee7}#currentAssets .asset-group-head h3{margin:0}#currentAssets .asset-table-wrap{overflow-x:auto}#currentAssets table{width:100%;border-collapse:collapse;min-width:650px}#currentAssets th,#currentAssets td{padding:9px 10px;border-bottom:1px solid #eaecf0;text-align:left}#currentAssets th{font-size:.78rem;color:#667085;background:#fafafa}#currentAssets .amount{text-align:right}#currentAssets .asset-input{width:100%;border:1px solid transparent;background:transparent;padding:7px;border-radius:7px;font:inherit}#currentAssets .asset-input:focus{border-color:#98a2b3;background:#fff;outline:none}#currentAssets .asset-input.amount{text-align:right}#currentAssets .asset-delete{border:0;background:transparent;color:#d92d20;cursor:pointer}#currentAssets .asset-add{border:1px solid #98a2b3;background:white;border-radius:8px;padding:7px 10px;cursor:pointer}#currentAssets .assets-note{font-size:.82rem;color:#667085}@media(max-width:800px){#currentAssets .assets-summary{grid-template-columns:repeat(2,minmax(135px,1fr))}#currentAssets .asset-card.total{grid-column:1/-1}}`;document.head.appendChild(s)}
function injectUI(){if($('currentAssets'))return;const nav=document.querySelector('.tabs');if(nav&&!document.querySelector('[data-view="currentAssets"]')){const b=document.createElement('button');b.className='tab';b.dataset.view='currentAssets';b.textContent='💰 Caja y activos';nav.appendChild(b)}const main=document.querySelector('main.container')||document.querySelector('main')||document.body;const sec=document.createElement('section');sec.id='currentAssets';sec.className='view';sec.innerHTML=`<div class="assets-head"><div><h2>💰 Caja y activos</h2><p>Efectivo, cheques, bancos y clientes particulares que deben.</p></div><button type="button" class="secondary" id="assetsReload">↻ Actualizar</button></div><div class="assets-summary"><div class="asset-card"><span>Caja</span><strong id="assetsTotalCash">$0</strong></div><div class="asset-card"><span>Cheques</span><strong id="assetsTotalChecks">$0</strong></div><div class="asset-card"><span>Bancos y billeteras</span><strong id="assetsTotalBanks">$0</strong></div><div class="asset-card"><span>Clientes particulares</span><strong id="assetsTotalClients">$0</strong></div><div class="asset-card total"><span>TOTAL ACTIVOS CORRIENTES</span><strong id="assetsGrandTotal">$0</strong></div></div><div id="assetsGroups"></div><p class="assets-note">Tocá el nombre, saldo u observación para editar. Se guarda al salir del campo o presionar Enter.</p>`;main.appendChild(sec);document.addEventListener('click',e=>{const tab=e.target.closest('[data-view="currentAssets"]');if(!tab)return;document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));sec.classList.add('active');tab.classList.add('active');loadAssets(true)});$('assetsReload')?.addEventListener('click',()=>loadAssets(true))}
function totals(){const sum=t=>rows.filter(r=>r.asset_type===t).reduce((a,r)=>a+num(r.balance),0);const a=sum('cash'),b=sum('checks'),c=sum('bank'),d=sum('personal_receivable');$('assetsTotalCash').textContent=money(a);$('assetsTotalChecks').textContent=money(b);$('assetsTotalBanks').textContent=money(c);$('assetsTotalClients').textContent=money(d);$('assetsGrandTotal').textContent=money(a+b+c+d)}
function render(){const host=$('assetsGroups');if(!host)return;host.innerHTML=Object.entries(TYPES).map(([type,label])=>{const rs=rows.filter(r=>r.asset_type===type).sort((a,b)=>num(a.sort_order)-num(b.sort_order)||String(a.name).localeCompare(String(b.name)));return `<section class="asset-group"><div class="asset-group-head"><h3>${esc(label)}</h3><button type="button" class="asset-add" data-add-asset="${esc(type)}">＋ Agregar</button></div><div class="asset-table-wrap"><table><thead><tr><th>Cuenta / cliente</th><th class="amount">Saldo</th><th>Observación</th><th></th></tr></thead><tbody>${rs.length?rs.map(r=>`<tr data-asset-id="${esc(r.id)}"><td><input class="asset-input" data-field="name" value="${esc(r.name)}"></td><td><input class="asset-input amount" data-field="balance" inputmode="decimal" value="${esc(num(r.balance))}"></td><td><input class="asset-input" data-field="notes" value="${esc(r.notes||'')}"></td><td><button type="button" class="asset-delete" data-delete-asset="${esc(r.id)}">🗑</button></td></tr>`).join(''):'<tr><td colspan="4">Todavía no hay registros.</td></tr>'}</tbody></table></div></section>`}).join('');totals()}
async function saveRow(r){r.updated_at=new Date().toISOString();try{if(cloud()){const {error}=await cloud().from(TABLE).upsert(r);if(error)throw error}localWrite()}catch(e){alert('No se pudo guardar el cambio. '+(e.message||e))}}
async function removeRow(id){const r=rows.find(x=>x.id===id);if(!r||!confirm(`¿Eliminar "${r.name}"?`))return;try{if(cloud()){const {error}=await cloud().from(TABLE).delete().eq('id',id);if(error)throw error}rows=rows.filter(x=>x.id!==id);localWrite();render()}catch(e){alert('No se pudo eliminar. '+(e.message||e))}}
async function addRow(type){const max=rows.filter(r=>r.asset_type===type).reduce((m,r)=>Math.max(m,num(r.sort_order)),0);const now=new Date().toISOString();const r={id:uuid(),asset_type:type,name:type==='personal_receivable'?'NUEVO CLIENTE':'NUEVA CUENTA',balance:0,notes:'',sort_order:max+10,created_at:now,updated_at:now};rows.push(r);localWrite();render();await saveRow(r);setTimeout(()=>{const i=document.querySelector(`[data-asset-id="${r.id}"] [data-field="name"]`);i?.focus();i?.select()},0)}
function bind(){document.addEventListener('keydown',e=>{const i=e.target.closest('#currentAssets .asset-input');if(i&&e.key==='Enter'){e.preventDefault();i.blur()}});document.addEventListener('change',async e=>{const i=e.target.closest('#currentAssets .asset-input');if(!i)return;const tr=i.closest('[data-asset-id]');const r=rows.find(x=>x.id===tr?.dataset.assetId);if(!r)return;const f=i.dataset.field,v=f==='balance'?num(i.value):i.value.trim();if(r[f]===v)return;r[f]=v;localWrite();totals();await saveRow(r)});document.addEventListener('click',e=>{const a=e.target.closest('[data-add-asset]');if(a)addRow(a.dataset.addAsset);const d=e.target.closest('[data-delete-asset]');if(d)removeRow(d.dataset.deleteAsset)})}
async function loadAssets(show=false){try{if(cloud()){const {data,error}=await cloud().from(TABLE).select('*').order('sort_order',{ascending:true});if(error)throw error;rows=data||[]}else rows=localRead();if(!rows.length){rows=defaults();localWrite();if(cloud())await cloud().from(TABLE).upsert(rows)}localWrite()}catch(e){rows=localRead();if(!rows.length){rows=defaults();localWrite()}if(show)alert('No se pudo leer Caja y Activos desde Supabase. Se muestra la copia local. '+(e.message||e))}render()}
function init(){injectStyles();injectUI();bind();loadAssets(false)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
